### ISSUE TITLE
create a new updated release for homebrew

### ISSUE THREAD

**Issue by shaharmor** [mhagger/git-when-merged#15]

**Comment by mhagger** [comment]
I just created a [v1.2.0 release](https://github.com/mhagger/git-when-merged/releases/tag/v1.2.0) from master. Is that enough to get you started?

FWIW I also created a [v1.1.1 release](https://github.com/mhagger/git-when-merged/releases/tag/v1.1.1) containing bugfixes for 1.1.0, not that anybody is likely to care.

/cc @knpwrs, @stevemao who've done homebrewey things before.
