### ISSUE TITLE
Publish on pypi

### ISSUE THREAD

**Issue by mattiasb** [mhagger/git-when-merged#18]
I would like to test this out, but also with as little effort as possible.

Would it be possible to publish this on pypi? That way to try it out is just: 
```
$ pip install --user git-when-merged
```

It would imply adding a setup.py file.

For extra points, adding an entrypoints section, like this:
```python
     entry_points={
        'console_scripts': [
            'git-merged-when=git-merged-when:main',
        ],
    },
```
...would make it work in windows as well.

**Comment by tucked** [comment]
I'm happy to do the packaging.

@mhagger if I open a PR, will you publish this? I can include automation that pushes to PyPI automatically whenever a tag is created if that'd be helpful.

**Comment by mhagger** [comment]
@tucked: thanks, that would be helpful. Bonus points if the instructions are simple enough that a 5-year-old can understand them, since I've not been active in the Python community for more than five years :wink:

**Comment by tucked** [comment]
https://pypi.org/project/git-when-merged/

Woohoo! Thanks @mhagger 😎
