### ISSUE TITLE
publish this to homebrew?

### ISSUE THREAD

**Issue by stevemao** [mhagger/git-when-merged#5]
Make it easy to install

**Comment by mhagger** [comment]
I have no objections if somebody steps up to do it.

**Comment by knpwrs** [comment]
I was actually just looking at doing this but there doesn't appear to be any versioning that I can see. @mhagger, would you be willing to tag a v1.0.0 release?

**Comment by mhagger** [comment]
@knpwrs: I just created a v1.0.0 tag. Let me know if you need anything else.

**Comment by knpwrs** [comment]
Submitted: https://github.com/Homebrew/homebrew/pull/48018

**Comment by mhagger** [comment]
> Submitted: https://github.com/Homebrew/homebrew/pull/48018

:heart: Awesome!

**Comment by knpwrs** [comment]
Merged over in Homebrew/homebrew#48018. This can be closed now.

**Comment by stevemao** [comment]
@knpwrs docs are missing. I can send a PR when I have time.
